version: '3.1'

services:
  db:
    image: postgres:13.7
    privileged: true
    restart: always
    ports:
      - 54328:5432
    environment:
        POSTGRES_DB: 'drf'
        POSTGRES_USER: 'root'
        POSTGRES_PASSWORD: '1234'

  backend:
    build: ./drf
    privileged: true
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    command: bash -c "
        python manage.py migrate &&
        gunicorn drf.wsgi -b 0.0.0.0:8080
      "
    environment:
      DJANGO_SETTINGS_MODULE: drf.settings.production

  nginx:
    build: ./nginx
    privileged: true
    restart: always
    ports:
      - 8000:80
    depends_on:
      - backend

  frontend:
    build: ./drf/frontend
    privileged: true
    restart: always
    ports:
      - 80:80
    depends_on:
      - nginx